version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: psqluser
      POSTGRES_PASSWORD: psqlpass
      POSTGRES_DB: covid19-project
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: